<a href="https://colab.research.google.com/github/DaitTan/LabCodebase/blob/main/Lab12/Python_basics_04102024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This code is from https://github.com/jupyter/mozfest15-training/blob/master/00-python-intro.ipynb

All credits to them!

### 1 Use an operator

All of the basic math operators work like you think they should for numbers. They can also
do some useful operations on other things, like strings. There are also boolean operators that
compare quantities and give back a `bool` variable as a result.

In [1]:
# Standard math operators work as expected on numbers
a = 2
b = 3
print(a + b)
print(a * b)
print(a ** b)  # a to the power of b (a^b does something completely different!)
print(a / b)   # Careful with dividing integers if you use Python 2

5
6
8
0.6666666666666666


In [2]:
# There are also operators for strings
print('hello' + 'world')
print('hello' * 3)
#print('hello' / 3)  # You can't do this!

helloworld
hellohellohello


In [3]:
# Boolean operators compare two things
a = (1 > 3)
b = (3 == 3)
print(a)
print(b)
print(a or b)
print(a and b)

False
True
True
False


### 2 Use a function

These will be very familiar to anyone who has programmed in any language, and work like you
would expect.

In [4]:
# There are thousands of functions that operate on things
print(type(3))
print(len('hello'))
print(round(3.3))

<class 'int'>
5
3


In [5]:
round(3.14159, 2)

3.14

__TIP:__ Many useful functions are not in the Python built in library, but are in external
scientific packages. These need to be imported into your Python notebook (or program) before
they can be used. Probably the most important of these are numpy and matplotlib.

In [6]:
# Many useful functions are in external packages
# Let's meet numpy
import numpy as np

In [7]:
# Some examples of numpy functions and "things"
print(np.sqrt(4))
print(np.pi)  # Not a function, just a variable
print(np.sin(np.pi))

2.0
3.141592653589793
1.2246467991473532e-16


### Exercise 1 - Conversion

The first thing we want to do is convert from `inches` to `metres`.

To change inches into metres we use the following equation (conversion factor is rounded)

## $metre = \frac{inches}{39.3700787}$

1. Create a variable for the conversion factor, called `conversion_factor`.
1. Create a variable (`inches`) for your height in inches, as inaccurately as you want.
2. Divide `inches` by `conversion_factor`, and store the result in a new variable, `metres`.
1. Print the result

__Bonus__

Write a function `inches_to_cm` that takes an input `height` in inches and outputs height in cm. We know that 1 metre = 100 cm.


### Exercise 2 - Lets deal with a List

1. Ask 5 people around for their heights in inches (or just put in reasonable integers) and put them in a list.
2. Use the function defined above to convert them to cm

__Tip__
You would be using a loop maybe?


### 3 Numpy arrays (ndarrays)

Even though numpy arrays (often written as ndarrays, for n-dimensional arrays) are not part of the
core Python libraries, they are so useful in scientific Python that we'll include them here in the
core lesson. Numpy arrays are collections of things, all of which must be the same type, that work
similarly to lists (as we've described them so far). The most important are:

1. You can easily perform elementwise operations (and matrix algebra) on arrays
1. Arrays can be n-dimensional
1. There is no equivalent to append, although arrays can be concatenated

Arrays can be created from existing collections such as lists, or instantiated "from scratch" in a
few useful ways.

When getting started with scientific Python, you will probably want to try to use ndarrays whenever
possible, saving the other types of collections for those cases when you have a specific reason to use
them.

In [9]:
# We need to import the numpy library to have access to it
# We can also create an alias for a library, this is something you will commonly see with numpy
import numpy as np

In [10]:
# Make an array from a list
alist = [2, 3, 4]
blist = [5, 6, 7]
a = np.array(alist)
b = np.array(blist)
print(a, type(a))
print(b, type(b))

[2 3 4] <class 'numpy.ndarray'>
[5 6 7] <class 'numpy.ndarray'>


In [11]:
# Do arithmetic on arrays
print(a**2)
print(np.sin(a))
print(a * b)
print(a.dot(b), np.dot(a, b))

[ 4  9 16]
[ 0.90929743  0.14112001 -0.7568025 ]
[10 18 28]
56 56


In [12]:
# Boolean operators work on arrays too, and they return boolean arrays
print(a > 2)
print(b == 6)

c = a > 2
print(c)
print(type(c))
print(c.dtype)

[False  True  True]
[False  True False]
[False  True  True]
<class 'numpy.ndarray'>
bool


In [13]:
# Indexing arrays
print(a[0:2])

c = np.random.rand(3,3)
print(c)
print('\n')
print(c[1:3,0:2])

c[0,:] = a
print('\n')
print(c)

[2 3]
[[0.85206712 0.41153213 0.98222641]
 [0.18194541 0.45669799 0.03189521]
 [0.51011834 0.58350902 0.17719921]]


[[0.18194541 0.45669799]
 [0.51011834 0.58350902]]


[[2.         3.         4.        ]
 [0.18194541 0.45669799 0.03189521]
 [0.51011834 0.58350902 0.17719921]]


In [14]:
# Arrays can also be indexed with other boolean arrays
print(a)
print(b)
print(a > 2)
print(a[a > 2])
print(b[a > 2])

b[a == 3] = 77
print(b)

[2 3 4]
[5 6 7]
[False  True  True]
[3 4]
[6 7]
[ 5 77  7]


In [18]:
# ndarrays have attributes in addition to methods
#c.
print(c)
print(c.shape)
print(c.prod())
print(c.sum())

[[2.         3.         4.        ]
 [0.18194541 0.45669799 0.03189521]
 [0.51011834 0.58350902 0.17719921]]
(3, 3)
0.003354958873510887
10.941365178909077


In [19]:
# There are handy ways to make arrays full of ones and zeros
print(np.zeros(5), '\n')
print(np.ones(5), '\n')
print(np.identity(5), '\n')

[0. 0. 0. 0. 0.] 

[1. 1. 1. 1. 1.] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 



In [20]:
# You can also easily make arrays of number sequences
print(np.arange(0, 10, 2))

[0 2 4 6 8]


### EXERCISE 3 - Using Arrays for simple analysis

Revisit your list of heights

1. turn it into an array
2. calculate the mean
4. find the mean of the masked heights

__BONUS__

1. I want you to use .sum() and division to do this
